# Generated by Django 4.0.1 on 2022-01-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20200107_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
