# Generated by Django 3.0.1 on 2020-01-01 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Caledars',
                'verbose_name_plural': 'Calendars',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.Calendar', verbose_name='Calendar')),
            ],
            options={
                'verbose_name': 'Event category',
                'verbose_name_plural': 'Event categories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Published')], default=2, help_text='With Draft chosen, will only be shown for admin users on the site.', verbose_name='State')),
                ('version', models.PositiveSmallIntegerField(verbose_name='Version')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.Calendar', verbose_name='Calendar')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
