# Generated by Django 4.2.4 on 2023-08-06 14:21

import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Icon')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('default', models.BooleanField(default=False, verbose_name='Default')),
                ('auto_update', models.BooleanField(default=False, verbose_name='Auto update calendar')),
            ],
            options={
                'verbose_name': 'Calendar',
                'verbose_name_plural': 'Calendars',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('bg_color', colorful.fields.RGBColorField(blank=True, null=True, verbose_name='Background color')),
                ('color', colorful.fields.RGBColorField(blank=True, null=True, verbose_name='Color')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Street',
                'verbose_name_plural': 'Streets',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('state', models.IntegerField(choices=[(1, 'Draft'), (2, 'Published')], default=2, help_text='With Draft chosen, will only be shown for admin users on the site.', verbose_name='State')),
                ('version', models.PositiveSmallIntegerField(default=0, verbose_name='Version')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='event.calendar', verbose_name='Calendar')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.AddField(
            model_name='calendar',
            name='categories',
            field=models.ManyToManyField(to='event.category', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.city', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='street',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='city', chained_model_field='city', on_delete=django.db.models.deletion.CASCADE, to='event.street', verbose_name='Street'),
        ),
    ]
