# Generated by Django 4.2.10 on 2024-02-27 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.street', verbose_name='Street'),
        ),
    ]
