# Generated by Django 4.2.4 on 2023-08-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_street_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
