# Generated by Django 5.1.4 on 2024-12-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_calendar_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='item_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='city',
            name='item_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='street',
            name='item_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID'),
        ),
    ]
