# Generated by Django 3.0.1 on 2020-01-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20200101_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Icon'),
        ),
    ]
