# Generated by Django 3.0.1 on 2020-01-01 16:55

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20200101_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=colorful.fields.RGBColorField(blank=True, null=True, verbose_name='Color'),
        ),
    ]
