# Generated by Django 3.0.1 on 2020-01-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_category_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='icon',
        ),
        migrations.AddField(
            model_name='calendar',
            name='char',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Character'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Icon'),
        ),
    ]
