# Generated by Django 3.0.1 on 2020-01-01 17:24

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20200101_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bg_color',
            field=colorful.fields.RGBColorField(blank=True, null=True, verbose_name='Background color'),
        ),
    ]
