# Generated by Django 3.0.1 on 2020-01-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20200101_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Default'),
        ),
        migrations.AddField(
            model_name='location',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Default'),
        ),
    ]
