# Generated by Django 3.0.1 on 2020-01-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20200102_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'verbose_name': 'Calendar', 'verbose_name_plural': 'Calendars'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AddField(
            model_name='calendar',
            name='locations',
            field=models.ManyToManyField(to='event.Location'),
        ),
    ]
