# Generated by Django 3.0.1 on 2020-01-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_auto_20200102_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='default',
        ),
    ]
