# Generated by Django 3.0.1 on 2020-01-02 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_remove_location_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='def_loc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default', to='event.Location', verbose_name='Default location'),
        ),
    ]
